let fruits = ['apple', 'banana', 'cherry'];
console.log(fruits)
fruits.push('grape')
console.log(fruits)
fruits.pop()
console.log(fruits)
fruits.unshift('mango')
console.log(fruits)
fruits.shift()
console.log(fruits)